language: bash

services:
  - docker

matrix:
  include:
  - name: "PHP: 7.1, OS: stretch"
    env:  PHP_VERSION=7.1 OS_VERSION=stretch
  - name: "PHP: 7.2, OS: alpine3.9"
    env:  PHP_VERSION=7.2 OS_VERSION=alpine3.9
  - name: "PHP: 7.2, OS: stretch"
    env:  PHP_VERSION=7.2 OS_VERSION=stretch
  - name: "PHP: 7.3, OS: alpine3.9"
    env:  PHP_VERSION=7.3 OS_VERSION=alpine3.9
  - name: "PHP: 7.3, OS: stretch"
    env:  PHP_VERSION=7.3 OS_VERSION=stretch

install:
  - make ${PHP_VERSION}-${OS_VERSION}-build

script:
  - make ${PHP_VERSION}-${OS_VERSION}-test-version
  - make ${PHP_VERSION}-${OS_VERSION}-test-info

notifications:
  email: false
