language: bash

services:
  - docker

env:
  - PHP_EXT=bcmath
  - PHP_EXT=bz2

install:
  - docker build -t my/php:7.3-stretch-${PHP_EXT} 7.3/stretch/${PHP_EXT}

script:
  - docker run -it --rm my/php:7.3-stretch-${PHP_EXT} php --version
  - docker run -it --rm my/php:7.3-stretch-${PHP_EXT} php -i | grep -i $(echo ${PHP_EXT} | sed -e 's|pecl_||')

notifications:
  email: false
