language: bash

services:
  - docker

env:
  - PHP_EXT=bcmath
  - PHP_EXT=bz2

matrix:
  include:
  - name: "7.2 stretch"
    env: PHP_VERSION=7.2 OS_VERSION=stretch
  - name: "7.3 stretch"
    env: PHP_VERSION=7.3 OS_VERSION=stretch

install:
  - docker build -t my/php:${PHP_VERSION}-${OS_VERSION}-${PHP_EXT} ${PHP_VERSION}/${OS_VERSION}/${PHP_EXT}

script:
  - docker run -it --rm my/php:${PHP_VERSION}-${OS_VERSION}-${PHP_EXT} php --version
  - docker run -it --rm my/php:${PHP_VERSION}-${OS_VERSION}-${PHP_EXT} php -i | grep -i $(echo ${PHP_EXT} | sed -e 's|pecl_||')

notifications:
  email: false
