language: bash

services:
  - docker

matrix:
  include:
  - name: "PHP: 7.3, OS: alpine3.13"
    env:  PHP_VERSION=7.3 OS_VERSION=alpine3.13
  - name: "PHP: 7.3, OS: buster"
    env:  PHP_VERSION=7.3 OS_VERSION=buster
  - name: "PHP: 7.4, OS: alpine3.13"
    env:  PHP_VERSION=7.4 OS_VERSION=alpine3.13
  - name: "PHP: 7.4, OS: buster"
    env:  PHP_VERSION=7.4 OS_VERSION=buster
  - name: "PHP: 8.0, OS: alpine3.13"
    env:  PHP_VERSION=8.0 OS_VERSION=alpine3.13
  - name: "PHP: 8.0, OS: buster"
    env:  PHP_VERSION=8.0 OS_VERSION=buster

install:
  - make ${PHP_VERSION}-${OS_VERSION}-build

script:
  - make ${PHP_VERSION}-${OS_VERSION}-test-version
  - make ${PHP_VERSION}-${OS_VERSION}-test-module
  - make ${PHP_VERSION}-${OS_VERSION}-test-info
  - make ${PHP_VERSION}-${OS_VERSION}-test-tmp-files

notifications:
  email: true
