name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: "PHP: ${{ matrix.php_version }}, OS: ${{ matrix.os_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3", "7.4", "8.0", "8.1"]
        os_version: ["alpine3.14", "bullseye", "buster"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.5
      -
        name: Build
        run: make build PHP_V=${{ matrix.php_version }} OS_V=${{ matrix.os_version }}
      -
        name: Test version
        run: make test-version PHP_V=${{ matrix.php_version }} OS_V=${{ matrix.os_version }}
      -
        name: Test module
        run: make test-module PHP_V=${{ matrix.php_version }} OS_V=${{ matrix.os_version }}
      -
        name: Test info
        run: make test-info PHP_V=${{ matrix.php_version }} OS_V=${{ matrix.os_version }}
      -
        name: Test tmp files
        run: make test-tmp-files PHP_V=${{ matrix.php_version }} OS_V=${{ matrix.os_version }}
