name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.3", "7.4", "8.0"]
        os_version: ["alpine3.13", "buster"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Build
        run: make ${{ matrix.php_version }}-${{ matrix.os_version }}-build
      -
        name: Test version
        run: make ${{ matrix.php_version }}-${{ matrix.os_version }}-test-version
      -
        name: Test module
        run: make ${{ matrix.php_version }}-${{ matrix.os_version }}-test-module
      -
        name: Test info
        run: make ${{ matrix.php_version }}-${{ matrix.os_version }}-test-info
      -
        name: Test tmp files
        run: make ${{ matrix.php_version }}-${{ matrix.os_version }}-test-tmp-files
